travis:
  secure:
    BINSTAR_TOKEN: VxklWSSoTeJk5I94w2lthmgVxpguzqOecpk/o2g/RdJz9rD3ocjxMTIzJ9BxB4Y6oXvLS21NHSE4MSApj3FUaksg8N7Cb6PPMONM3yUZ/s+zHVim5L/1rfpW412xG8sOs1Mn7IOuLeFn++1xXIW2BRujLw7m5DyWusdv/if6/j3VLo6IdoB0vaMyiiPhsyAhQ8vGNkTO7JWtOArt3ICnvhbI9Z3YLnVHMFAxdwAudBHESvCYILcI8DUbj8UYtY5KpJuTodNMEB17XBfvNNP1Bqoy4RRdoNj+tbxbIwDHeOq8Iskk5jfz28ohMXK3SINMsEVcF9/e/77DvkKHdOEh0KXPf9Ww/Vr+oesX1jq3mCee8zycTwSv5EUb8K2YZAxRYnku1dNWae2VSJ7kqN/+Rd2aqzGB0Jrl1H7pQpzzeYVMzgSnpfBlzDWrvUXofVoBEaFDqaeMqfSAR1bFjA6mw5e7qonM3hb/fBHF/oLufv709gUYbXVb0cE7r8bGuztfNdnYOug+NMfjV2jxsHlOHTxW50+4rbHha6q9RXXsdY4XsAom3/2vji2qptrepA3XNWfp7YT5WfTkCIK+JACHswMkWtxFy6hBc+lyK4btf2u8focuMd5CZc6r6r7OPY+hUrdVjobyg+JkBPBS8F4wtmKAMZHcbgkxD8ZE0+tZFfc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
